vich_uploader:
  db_driver: orm
  metadata:
    type: attribute
  mappings:
    shelf_image:
      uri_prefix: '%app.path.shelf_image%'
      upload_destination: '%kernel.project_dir%/public%app.path.shelf_image%'
      namer: Vich\UploaderBundle\Naming\HashNamer
      inject_on_load: true
